name: NeoGear
main: me.neoblade298.neogear.Gear
author: [Neoblade298]
depend: [SkillAPI, Vault]
version: 1.0
api-version: 1.14
commands:
   gear:
      description: Does its job
      usage: /gear
      permission: neogear.admin